_content/integration/deploy-kafka.md

replace Aspera with Event Streams

Up date deploy-kafka.md

---

_content/integration/deploy-integration.md
_content/integration/deploy-queue-manager.md
_content/integration/deploy-tracing.md
_content/integration/introduction.md
_content/integration/onprem-offline.md
_content/integration/onprem-online.md

few fixes for images and testing approval flow

minor fixes

---

_content/automation/install-bas.md
_content/automation/install-operator.md
_content/automation/install-ums.md
_content/automation/introduction.md
assets/automation/bas/bas-secret.yaml
assets/automation/bas/my_ibm_cp4a_cr_2.yaml
assets/automation/bas/playback-ae-server.yaml
assets/automation/bas/rr-secret.yaml
assets/automation/operator/my_ibm_cp4a_cr_0.yaml
assets/automation/operator/operator-shared-pv.yaml
assets/automation/operator/operator-shared-pvc.yaml
assets/automation/ums/my_ibm_cp4a_cr_1.yaml
assets/automation/ums/ums-secret.yaml

Additions for Operator, UMS, BAS

Initial commit for 19.0.3 on OCP 4.2

---

_config.yml

Reverts ibm-cloud-architecture/cloudpak8s#19

Revert "Update github URL for proposed changes"

---

_content/integration/deploy-integration.md

some new appcon changes

---

_content/integration/introduction.md
_content/integration/onprem-online.md
_content/integration/pre-reqs.md

Far from finished, but I've been updating the docs to improve readability, incorporate some knowledge from CPAT UKI and make sure that it's all passing a linter :)
Not going to be able to do much for the next few days, so I figured I may as well make a pull request now.

CP4I Docs update

---

_content/integration/onprem.md

Fixed the file path to be "installer_files" instead of "installer".

fixed file path

---

src/pages/mcm/cp4mcm_mcm_install/index.mdx

I updated the MCM Install doc with a few minor corrections and updated formatting.

Updated MCM Install section

---

gatsby-browser.js
src/data/nav-items.yaml
src/gatsby-theme-carbon/components/Footer.js
src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
src/pages/contribute/index.mdx
src/pages/index.mdx
src/pages/playbook/index.mdx
src/pages/support/index.mdx
src/styles/global.css

Implemented the nice formatting changes from MCM Bootcamp site. Also tidied up some footer and left navigation bar links. Made links to the issues page and contribution guide from the front page disclaimer.

Improvement of contribution guide

---

src/pages/integration/onprem-offline/index.mdx

Added the instructions for installing CP4Integration offline. fixes #71

Added CP4Integration offline installation instructions

---

src/pages/integration/onprem-offline/index.mdx

Remove internal URL CP4I

---

src/pages/contribute/index.mdx

Added in changes for non-Mac users in src/pages/contribute (testing locally) section

changes in test locally

---

src/pages/contribute/index.mdx

Updated more specific explanation

Testing locally

---

src/pages/integration/onprem-offline/index.mdx

Just added a quick check. Nothing major.

added docker login check

---

src/pages/mcm/cp4mcm_mcm_install/index.mdx

Added installation instructions for CP4MCM1.3

Updated to include Cloud Pak version 1.3

---

src/pages/mcm/cp4mcm_mcm_install/index.mdx

Everyone should be using the new process to get their entitled key. I updated an old links to point to the new process.

Updated CP4MCM install with entitled key instructions

---

src/pages/integration/deploy-secure-gateway/index.mdx

Added port-forward instructions to access web UI locally for Issue #86

Added DataPower web UI access steps

---

src/pages/security/install/index.mdx
src/pages/security/introduction/index.mdx
src/pages/security/prereq/index.mdx

Major update to Cloud Pak for Security for new release 1.2. Installation instructions are simplified somewhat.

Update for CP4S 1.2

---

src/pages/mcm/cp4mcm_cam_install/index.mdx
src/pages/mcm/cp4mcm_cloudforms/index.mdx
src/pages/mcm/cp4mcm_icam_install/index.mdx
src/pages/mcm/cp4mcm_mcm_install/index.mdx

Potentially wrong also for 1.2 but I do not have the system to verify

MCM 1.3 offline install has wrong container name

---

src/data/nav-items.yaml
src/pages/mcm/cp4mcm_cloudforms/index.mdx
src/pages/playbook/index.mdx

Was missing an entry in the nav file to make the CloudForms chapter appear. Also made grammatical and formatting corrections in the CloudForms chapter, and fixed a picture link on the Playbook home page.

Fix MCM to show CloudForms chapter

---

src/data/nav-items.yaml
src/pages/mcm/cp4mcm_icam_install/index.mdx
src/pages/mcm/cp4mcm_mcm_install/index.mdx
src/pages/mcm/edge/index.mdx
src/pages/playbook/index.mdx

Added section on installing IBM Edge Computing Manager for Devices to MCM section. Also fixed a problem where code blocks were not formatting correctly when inside tabs.

MCM add Edge Computing fix formatting

---

src/pages/contribute/index.mdx
src/pages/playbook/index.mdx

Adding some more detail to some of the descriptions to be more explicit and more specific to our repo. Hopefully this will help other contributors to contribute without fear.

Add more detail to Contribution Guide

---

src/pages/mcm/edge/index.mdx

Had a few bad indents in the Post installation config section I fixed. Also added anchor links.

Edge Fix format add anchor links

---

README.md

Thanks for the heads up @jdiggity22 . Just added this build link capability. Please review when you can.

Add build status icon & link to README

---

src/pages/ocp/openshift4_aws/index.mdx

Based on issues encountered during recent client engagement, I added a troubleshooting section to the OCP on AWS page for future growth.

Added troubleshooting section for OCP on AWS

---

src/pages/ocp/openshift4_aws/index.mdx

Had to fix numbering format in Solution section so steps are not all in 1 paragraph. Just added a line between each step.

Fix formatting in AWS OCP section

---

src/pages/mcm/cp4mcm_icam_install/index.mdx

Installation image script did not have proper formatting. Adjusted formatting to properly display on live website

Loading installation image script not formattted

---

src/pages/automation/pre-requisites/index.mdx

Added Expose OCP Docker registry step @pberlandier

Update index.mdx. expose OCP Docker registry

---

src/pages/apps/cp4a_use_case_app_mod/index.mdx

Added link to Getting started with Mobile Foundation on OpenShift

Added link to tutorial for Mobile Foundation

---

src/pages/apps/cp4a_installation/index.mdx

Updated links to point to 4.1 CP4A links, added info related to Mobile Foundation in CP4A.

Proposing changes wrt CP4A 4.1 release

---

src/pages/apps/cp4a-prereq/index.mdx
src/pages/integration/cp4i-introduction/index.mdx
src/pages/news/index.mdx
src/pages/playbook/index.mdx

Requesting review and merge from @jdiggity22 . Mostly just updating What's New for latest updates and fixing a few documentation links.

Update Whats New page and various doc links

---

src/pages/mcm/cp4mcm_governance_risk/index.mdx

Issue #83 had been open for a while, so I just went ahead and addressed it. Also did some grammar fixes and added anchor links to that page. @jdiggity22 please review.

Update MCM Governance page for issues in #83

---

src/pages/apps/cp4a_installation/index.mdx
src/pages/apps/cp4a_learn_more/index.mdx
src/pages/apps/cp4a_overview/index.mdx

Remove references to Kabanero

---

src/data/nav-items.yaml

Just commenting out unfinished sections for CP for Automation so they do not show up on the site but are not deleted so they can be completed.

Hide unfinished automation sections

---

src/data/nav-items.yaml
src/pages/integration/cp4i-deploy-api-mgmt/index.mdx
src/pages/integration/cp4i-deploy-app-int/index.mdx
src/pages/integration/cp4i-deploy-asset-repo/index.mdx
src/pages/integration/cp4i-deploy-eventstreams/index.mdx
src/pages/integration/cp4i-deploy-fast-file-transfer/index.mdx
src/pages/integration/cp4i-deploy-mq/index.mdx
src/pages/integration/cp4i-deploy-secure-gateway/index.mdx
src/pages/integration/cp4i-deploy-tracing/index.mdx
src/pages/integration/cp4i-install/index.mdx
src/pages/integration/cp4i-introduction/index.mdx
src/pages/integration/cp4i-requirements/index.mdx
src/pages/integration/scripts/index.mdx
src/pages/news/index.mdx

Added section containing link to command line scripts to install CP4I capabilities, and also Tekton pipelines.
Also made existing sections consistent using anchor links.
Added new item to the News page.
Requesting review from @vbudi000

CP4I Scripts Pipelines & general cleanup

---

src/pages/integration/cp4i-deploy-api-mgmt/index.mdx
src/pages/integration/cp4i-deploy-asset-repo/index.mdx
src/pages/integration/cp4i-deploy-eventstreams/index.mdx
src/pages/news/index.mdx

Made 2020.1.1 updates to API Connect and Event Streams pages requested by @drmiller4 in issue #108 . Requesting review from @drmiller4 or @jabbott7335 .

cp4i fixes for issue #108

---

src/data/nav-items.yaml
src/pages/mcm/cp4mcm_netcool_ops_manager/index.mdx

Adding the Netcool Ops Manager

Netcool Ops Manager first commmit

---

.travis.yml
CNAME
src/pages/news/index.mdx

@csantanapr This includes the reconfig to move the site to cloudpak8s.io. Let's wait with it until we are done with our DNS work.

url migration

---

src/pages/day2/Introduction/index.mdx

update the introduction page to remove internal note and change font size of headers.

update the introduction page to remove internal note

---

src/pages/day2/User/UserLdap/index.mdx
src/pages/day2/User/UserRbac/index.mdx
src/pages/day2/User/UserVmware/index.mdx
src/pages/day2/User/index.mdx

Fixed various formatting and grammar issues in the 4 pages of the User section. Bolded new terms in the definitions, as well as objects being described. Requesting review from @kenuenoibm .

Fix format in User section

---

src/pages/day2/Introduction/index.mdx

Single picture link needed a fix. Requesting review from @Julius-F-Wahidin .

Fix image link on Day 2 Intro

---

src/pages/mcm/cp4mcm_nom_day2/index.mdx

Adding links to external blogs on ASM further configuration (Day-2) activities.

Adding links to ASM Day 2

---

src/pages/day2/Catalog/index.mdx

Updated the Catalog management chapter: removed comments and added new contents.

removed comments and added contents to the Catalog management chapter

---

src/pages/mcm/cp4mcm_mcm_install/index.mdx

Update to resolve this issue.  https://github.com/ibm-cloud-architecture/cloudpak8s/issues/177

Fixed config command identified in git issue.

---

src/pages/mcm/cp4mcm_cloudforms/index.mdx

Fixed link to an internal git repo related to this issue: https://github.com/ibm-cloud-architecture/cloudpak8s/issues/162

Updated bad link in the Configure LDAP section.

---

src/pages/mcm/cp4mcm_netcool_ops_manager/index.mdx
src/pages/news/index.mdx

minor spelling corrections and removal on the ldap reference to the no longer required common platform.

Minor spelling mistake and edit

---

gatsby-config.js
package.json

Adding 3 plugins to address mdx syntax failures (gatsby-plugin-mdx, gatsby-source-filesystem, gatsby-mdx-fix).

Update for mdx plugins

---

src/pages/mcm/cp4mcm_netcool_ops_manager/index.mdx

Small addition based on reader's comment/feedback.

small correctiong based on reader's question

---

src/pages/common_services/cs_install/index.mdx
src/pages/contribute/index.mdx
src/pages/day2/BuildDeploy/index.mdx
src/pages/day2/Scalability/index.mdx
src/pages/day2/Storage/index.mdx
src/pages/integration/cp4i-deploy-api-mgmt-2020.1.x/index.mdx
src/pages/integration/cp4i-deploy-asset-repo-2020.1.x/index.mdx
src/pages/integration/cp4i-deploy-eventstreams-2020.1.x/index.mdx
src/pages/integration/cp4i-deploy-fast-file-transfer-2020.1.x/index.mdx
src/pages/integration/cp4i-deploy-mq-2020.1.x/index.mdx
src/pages/integration/cp4i-deploy-secure-gateway-2020.1.x/index.mdx
src/pages/integration/cp4i-deploy-tracing-2020.1.x/index.mdx
src/pages/mcm/cp4mcm_cam_install/index.mdx
src/pages/mcm/cp4mcm_cloudforms/index.mdx
src/pages/mcm/cp4mcm_cloudforms_policies/index.mdx
src/pages/mcm/cp4mcm_icam_install/index.mdx
src/pages/mcm/cp4mcm_icam_post_server_install/index.mdx
src/pages/mcm/cp4mcm_netcool_ops_manager/index.mdx
src/pages/mcm/cp4mcm_netcool_ops_manager/noi_1603/index.mdx
src/pages/mcm/edge/index.mdx
src/pages/multipak/cp4i-cp4a/index.mdx
src/pages/ocp/openshift4_aws/index.mdx
src/pages/ocp/prereqs-openshift4/index.mdx
src/pages/security/install/index.mdx

After much trial and error, I found a workaround for this problem in Firefox. The problem is when there is a preceding unordered list anywhere in the file, the numbering index does not get reset for a following ordered list. This only occurs in the Firefox browser. The workaround is just to open and close an empty unordered list with html tags somewhere before the ordered list.
```
<ul>
</ul>
```
For spacing and formatting, it seems best to do this in the previous heading section from where the ordered list list is. I think I have corrected all occurrences of this problem on the site with this PR.
Requesting review and merge from @jdiggity22 .

Site fixing Firefox ordered list numbering

---

gatsby-config.js
package.json

Fixes to pull site out of search engines and hopefully produce a successful build. Will watch the test and request review from @jdiggity22 .

Remove from search and fix build problems

---

package.json

Updating plugin @babel/plugin-transform-spread to 7.12.1 to hopefully resolve build issue.

Update plugin @babel/plugin-transform-spread

---

src/pages/aiops/aimgr/install/index.mdx
src/pages/aiops/aimgr/slack/index.mdx

Some edits for AImgr sections of the documentation

Update aiops aimgr install and slack

---

.travis.yml

Updating Travis node version to 15.

Update travis node version
